### ISSUE TITLE
Feature Request: Add support to call the `gh` command interactively

### ISSUE THREAD

**Issue by stemar94** [cli/go-gh#114]
I would like to call `gh` interactively in order to use the already existing survey prompt functionality that comes with the standard features of `gh`.
With just `gh.Exec` I'm not able to access the interactive mode.

**Comment by samcoe** [comment]
@stemar94 Thanks for writing in. This seems like a nice feature, I am in favor of adding it.

**Comment by vilmibm** [comment]
this makes perfect sense, I'm +1

**Comment by mislav** [comment]
Completed in https://github.com/cli/go-gh/commit/026e976b60f91b35bd97a2d82914c24515dda127, thank you!
