### ISSUE TITLE
Support  gh http_unix_socket configuration option

### ISSUE THREAD

**Issue by samcoe** [cli/go-gh#2]
`gh` supports a `http_unix_socket` option that impacts how API requests get sent, we should take that configuration option into account up the API clients.

**Comment by Nimeshssd** [comment]
Express highway pe hu bhai onilel support thx<<>>>
>>>......600<<~~~~~~~~~~}♡♤◇♧♧♧♧♧♧☆☆☆☆☆☆☆☆☆☆★☆☆☆★☆☆☆☆☆☆☆>>>>>>>>>>>>>{》》》》》》》♤♤♤♤♤♤♤♤♤♤♤♤♤♤◇◇◇◇◇♡♡♡♡♡♡♧♣︎♧♧¤¤¤¤¤¤¤~~~~~~~~~

**Comment by Nimeshssd** [comment]
Nice

**Comment by Nimeshssd** [comment]
Good

**Comment by Nimeshssd** [comment]
Network problem chhe ke a

**Comment by Nimeshssd** [comment]
Onilel

**Comment by Nimeshssd** [comment]
Code>>>>>>>>>>>
!!!!~\\\\\\\\\\99.9
