### ISSUE TITLE
Status code extraction on response/error

### ISSUE THREAD

**Issue by sridharavinash** [cli/go-gh#4]
I had a quick question/feedback - I was wondering if a status code could be included along with the response from the gh.RESTClient().Get? 

for example I was making a call
```go
client, err := gh.RESTClient(options)
<snip>
err = client.Get("enterprises/avocado-corp/audit-log", &response)
Unfortunately err  cannot be type-casted to api.httperror since api.httperror is not exported, so I’d have to rely on string parsing to figure out the error code here. Alternatively api.httpError could be exported to api.HTTPError , in which case the caller can then typecast the error and get all the relevant bits in the struct and do things like retry on certain statusCodes etc.
e.g
err = client.Get(blah)
if err != nil {
    httpError := err.(*api.HttpError)
    if httpError.statusCode == 502 {
            ...retry
     }else{
            ...do something else
      }
}
```
or the other option would be to read the statusCode, if it’s set on the response.

Does that make sense?

I started a PR to export api.HttpError here - https://github.com/cli/go-gh/commit/6596865f9dfc7df98da40b6c74fe1b3e918e8d4c 

Thanks for reading ❤️ .

**Comment by samcoe** [comment]
Closed in https://github.com/cli/go-gh/pull/6, this will be available in the next release.
