### ISSUE TITLE
Change example_gh_test.go to package `gh_test`

### ISSUE THREAD

**Issue by mntlty** [cli/go-gh#87]
Being in the same package, the example test file can refer to functions such as `RESTClient` and `Exec` as local, as opposed to `gh.RESTClient` and `gh.Exec`. This presents some challenges:
- the examples cannot be copied as is
- it can be confusing to Go newcomers, who may not be familiar with how to solve the issue

I would like to suggest changing the package of the example file and updating the functions in it.

**Comment by mntlty** [comment]
A concrete implementation is in https://github.com/cli/go-gh/commit/114787b4c315071b4b7c8f2cb95256da09e44f3b in case this makes sense to others

**Comment by mislav** [comment]
Thanks for bringing this up. Will the examples still get rendered of on the main page of generated docs? If so, I'm in favor of this 👍

**Comment by mntlty** [comment]
@mislav  I ran `godoc -http=:6060` on the example branch, and it renders the examples while adding the `gh` package. Comparing local output for http://localhost:6060/pkg/github.com/cli/go-gh/#example_RESTClient_advanced

From trunk:

```go
opts := api.ClientOptions{
    Host:      "github.com",
    AuthToken: "xxxxxxxxxx", // Replace with valid auth token.
    Headers:   map[string]string{"Time-Zone": "America/Los_Angeles"},
    Log:       os.Stdout,
}
client, err := RESTClient(&opts)
if err != nil {
    log.Fatal(err)
}
response := []struct{ Name string }{}
err = client.Get("repos/cli/cli/tags", &response)
if err != nil {
    log.Fatal(err)
}
fmt.Println(response)
```

From the example branch:

```go
opts := api.ClientOptions{
    Host:      "github.com",
    AuthToken: "xxxxxxxxxx", // Replace with valid auth token.
    Headers:   map[string]string{"Time-Zone": "America/Los_Angeles"},
    Log:       os.Stdout,
}
client, err := gh.RESTClient(&opts)
if err != nil {
    log.Fatal(err)
}
response := []struct{ Name string }{}
err = client.Get("repos/cli/cli/tags", &response)
if err != nil {
    log.Fatal(err)
}
fmt.Println(response)
```

is there something else I should check for?

**Comment by mislav** [comment]
Nice, thanks for checking! Please send a PR for this 🙇

**Comment by mntlty** [comment]
done!
