### ISSUE TITLE
Flag for printing only GraphQL information

### ISSUE THREAD

**Issue by epanipinto** [cli/go-gh#90]
This project has made my work significantly easier, thank you! 

I am finding that often I am wanting to print only the GraphQL query & GraphQL variables but not the HTTP information. I know you can set `os.Setenv("GH_DEBUG", "api")` to print the GraphQL & HTTP information. I am finding that when I am developing my GraphQL struct that it would be useful to reduce some of the noise and only print out the GraphQL information.

**Comment by mislav** [comment]
@epanipinto Thanks for the feature request.

When you say "only GraphQL information", do you mean to avoid printing HTTP traffic like headers? What about the JSON response to a GraphQL query?

**Comment by samcoe** [comment]
Closing this as stale as original author as not elaborated on feature request.
