### ISSUE TITLE
Please provide fake api.GQLClient out of the box

### ISSUE THREAD

**Issue by discentem** [cli/go-gh#93]
It would be awesome to provide a fake out of the box for unit tests.

**Comment by samcoe** [comment]
@discentem Thanks for writing in with the feature request. Right now, we don't feel that we want to be prescriptive with how people test their `gh` extensions and providing a fake for the API clients would go against that philosophy. There are a number of different testing solutions out there, for example we use [gock](https://github.com/h2non/gock) in this project but in `cli/cli` repo we are more partial to using [moq](https://github.com/matryer/moq), and we think it is best to tailor the testing solution to the individual project.
