### ISSUE TITLE
Add a GraphQL Mutation with an `input` object to examples

### ISSUE THREAD

**Issue by mntlty** [cli/go-gh#98]
I noticed that there are no examples of Mutations in https://github.com/cli/go-gh/blob/trunk/example_gh_test.go

I think this is important for a few reasons:
- there's no mention of [Mutate](https://github.com/cli/go-gh/blob/da64a13f361b2a1b9a1eb5358b7d7eee7506f6a2/pkg/api/client.go#L127) in the examples or in the readme. including it in the examples may make it more discoverable
- unlike queries, many of the GitHub GraphQL mutations take an input object, for example the [addStar mutation](https://docs.github.com/en/graphql/reference/mutations#addstar) and its [input](https://docs.github.com/en/graphql/reference/input-objects#addstarinput). because this is a nested object, it has a different format than queries such as https://github.com/cli/go-gh/blob/da64a13f361b2a1b9a1eb5358b7d7eee7506f6a2/example_gh_test.go#L125 Figuring out the right Go syntax took me some time even when I had a properly formed GraphQL mutation to compare it to

If you agree, I'd be happy to open a PR to update, and would like to know:
1. is `addStar` a good reference, or is there another that looks better?
2. for `variables`, would it be better to use https://github.com/shurcooL/githubv4 or to use only standard types?
3. should the Readme also mention mutations, or is it sufficient to have them in the examples?

**Comment by mislav** [comment]
Great idea! Go ahead please.

1. `addStar` seems fine! Any simple mutation would do.
2. We like to use `githubv4` because it validates the input types.
3. No, the README doesn't need to showcase mutations.
